name: Test exercises

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          gem install minitest
      - name: Run tests
        run: |
          ruby -Ilib:test test/*
